[package]
name = "sshcerts"
version = "0.3.7"
authors = ["Mitchell Grenier <mitchell@confurious.io>"]
edition = "2018"
license-file = "LICENSE"
description = "A library for parsing, verifying, and creating SSH Certificates"
repository = "https://github.com/obelisk/sshcerts"
homepage = "https://github.com/obelisk/sshcerts"
keywords = ["ssh", "yubikey", "certs", "certificates"]
categories = ["authentication"]

[features]
default = []
yubikey = ["yubikey-piv"]

[dependencies]
base64 = "0.12.1"
log = "0.4"
ring = "0.16.9"

yubikey-piv = {version = "0.1.0", features = ["untested"], optional = true}

[dev-dependencies]
env_logger = "0.8.2"
hex = "0.4.2"
clap = "3.0.0-beta.2"
criterion = "0.3"

[[bench]]
name = "certs-per-second"
harness = false
required-features = ["yubikey"]

[[example]]
name = "yk-fingerprint"
required-features = ["yubikey"]

[[example]]
name = "yk-provision"
required-features = ["yubikey"]