[package]
name = "rustica-sshkey"
version = "0.1.0"
authors = ["Mitchell Grenier <mitchell@confurious.io>"]
edition = "2018"

[dependencies]
base64 = "0.12.1"
byteorder = "1.3.4"
hex = "*"
sha2 = "0.9.2"
ring = "0.16.9"

[[bin]]
name = "ssh-cert-info"
test = false
bench = false