[package]
name = "rustica-keys"
version = "0.3.0-alpha"
authors = ["Mitchell Grenier <mitchell@confurious.io>"]
edition = "2018"
license-file = "LICENSE"
description = "A library for parsing, verifying, and creating SSH Certificates"
repository = "https://github.com/obelisk/rustica-keys"
homepage = "https://github.com/obelisk/rustica-keys"
keywords = ["ssh", "yubikey", "certs", "certificates"]
categories = ["authentication"]

[dependencies]
base64 = "0.12.1"
byteorder = "1.3.4"
log = "0.4"
sha2 = "0.9.2"
ring = "0.16.9"
yubikey-piv = {version = "0.1.0", features = ["untested"]}

[dev-dependencies]
hex = "0.4.2"

[[bin]]
name = "ssh-cert-info"
test = false
bench = false

[[bin]]
name = "yk-fingerprint"
test = false
bench = false