name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  macos-build-test-yubikey:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --features="yubikey" --verbose
    - name: Run tests
      run: cargo test --verbose
  
  ubuntu-build-test-no-yubikey:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
